services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: webscraperdb
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      echo 'Waiting for database...';
      while ! nc -z db 3306; do
        sleep 1;
      done;
      echo 'Database ready';
      python manage.py migrate;
      python manage.py collectstatic --noinput;
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
