# Generated by Django 5.0.3 on 2024-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('corresponding_author', models.CharField(max_length=250)),
                ('corresponding_author_email', models.EmailField(max_length=250)),
                ('date', models.DateField()),
                ('authors', models.ManyToManyField(to='website.author')),
            ],
        ),
    ]
