# Generated by Django 5.0.3 on 2024-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pii',
            field=models.CharField(default='N/A', max_length=250),
        ),
    ]
